---
- name: Dev test playbook
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: root
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_version: "latest"
    runner_name: test_name
    runner_on_ghes: yes
    reinstall_runner: false
    hide_sensitive_logs: no
    runner_labels:
      - label1
      - repo-runner
  roles:
    - robertdebock.epel
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
