---
- name: Cleanup
  hosts: all
  become: yes
  vars:
    runner_user: root
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_org: yes
    runner_state: absent
  roles:
    - monolithprojects.github_actions_runner
