---
- name: Install Org Runner
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: root
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_org: yes
    runner_version: "2.330.0"
    runner_no_default_labels: true
    runner_labels:
      - testlabel1
      - testlabel2
  roles:
    - robertdebock.epel
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
