---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Workaround for RockyLinux
      when: ansible_distribution == 'Rocky'
      # Bug in some upstream distros, /etc/shadow has no file perms in container image
      ansible.builtin.file:
        path: /etc/shadow
        mode: "400"
