---
- name: Install Repo runner
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: root
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_version: "2.329.0"
    runner_labels:
      - label1
      - repo-runner
  roles:
    - robertdebock.epel
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"

# Run the playbook again with different labels and version to test
- name: Update Repo runner
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    runner_user: root
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    runner_version: "latest"
    hide_sensitive_logs: false
    runner_labels:
      - label1
      - repo-runner
      - label2
  roles:
    - robertdebock.epel
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
