---
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 0
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
    verify: verify.yml
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO:-ubuntu2404}-latest"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
verifier:
  name: ansible
scenario:
  name: repo
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence # Converge is testing two different versions of the runner
    - side_effect
    - verify
    - cleanup
    - destroy
